# Generated by Django 4.2.14 on 2024-09-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryDescripition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
