# Generated by Django 4.2.14 on 2024-09-17 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_categorydescripition'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=100),
        ),
    ]
