# Generated by Django 4.2.14 on 2024-09-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_task_category_alter_category_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryDescripition',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_category',
        ),
    ]
