# Generated by Django 4.2.14 on 2024-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_categorydescripition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('I', 'In Process'), ('C', 'Completed')], default='P', max_length=10),
        ),
    ]
