# Generated by Django 4.2.14 on 2024-09-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryDescripition',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.category'),
        ),
    ]
