# Generated by Django 4.2.14 on 2024-09-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_category_categorydescripition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryDescripition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
